module.exports = {
  secret: 'mkgflklngnklhymklnkngfdknglngfdbngfjklbnlfdnbgkldngfklbngfkldbnhgfklngfklnklgfdnbklgfdnb kldgfn klbgnfb klgfklnbmklgfdsnbkdfjnbgkldgfnbklgfnbgfklbjngfklbnksbndsklnbhgklgfdsnbklgfsdnbkgfdnbklnbksnbs'
} 